### ISSUE TITLE
Create step by step documentation of how to install libs on python focus on the QR script

### ISSUE THREAD

**Issue by ericksc** [pyloguna/qr_id#4]

**Comment by ericksc** [comment]
@Miguel-SS  revisa este issue.

Documenta los pasos. esto pude poner screenshots!

**Comment by ericksc** [comment]
```python
print
```

![image](https://user-images.githubusercontent.com/20059518/73581342-7805b800-444e-11ea-8258-9e2b4566edb6.png)

**Comment by Miguel-SS** [comment]
Ok, voy a desintalar los paquetes e instalarlos de nuevo para tomar capturas
