### ISSUE TITLE
Usando Python y tecnologías para el desarrollo WEB (HTML, CSS, javascript, o lo que se considere necesario)

### ISSUE THREAD

**Issue by ericksc** [pyloguna/qr_id#7]
Crear un portal en el cual se le pide el usuario y la contraseña para un usuario genérico.
	
	campos: 
login
		password

	validar ambos datos y entrar a una página dada.

**Comment by ericksc** [comment]
@pyloguna/app-layer

**Comment by ninjaoflight** [comment]
ver PR #11

**Comment by ninjaoflight** [comment]
Por sastisfacer #13 #12

**Comment by ninjaoflight** [comment]
validado en #14 #15 #16 #17
