### ISSUE TITLE
crear una clase (OOP) en el cual se integren métodos para: interacción con base de datos

### ISSUE THREAD

**Issue by ericksc** [pyloguna/qr_id#8]
En Python, 
crear una clase (OOP) en el cual se integren métodos para:
interacción con base de datos

CRUD

Crear tabla
lectura en tabla
Actualizacion
Borrado

tiene que interactuar con un engine de base de datos

pyodbc,
ceodbc,
turbodbc,

criterios de calidad
1- Unit test usando pytest

**Comment by ericksc** [comment]
@pyloguna/logic-layer

**Comment by ninjaoflight** [comment]
Se solucionara en la migracion a Django (#18 ) con posibilidad de uso de sqlworkbench
